apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: production
data:
  LOG_LEVEL: "INFO"
  RABBITMQ_URL: "amqp://rabbitmq:5672"
  FRONTEND_URL: "https://frontend.prpo.timhrovat.com"
