apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth
  namespace: production
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - auth.prpo.timhrovat.com
    secretName: auth-tls
  rules:
  - host: auth.prpo.timhrovat.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auth
            port:
              number: 8080
